"""Generate the dashboard classification tables from the canonical registry."""

from __future__ import annotations

import json
from pathlib import Path

from .statuses import STATUS_DEFINITIONS


HEADER = """\
// Generated by `npm run generate:statuses`.
// Do not edit this file; edit src/exohunt/status_registry.json instead.

"""


def _typescript_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_typescript() -> str:
    lines = [HEADER, "export const STATUS_REGISTRY = {\n"]
    for definition in STATUS_DEFINITIONS:
        lines.extend(
            [
                f"  {_typescript_string(definition.slug)}: {{\n",
                f"    label: {_typescript_string(definition.label)},\n",
                f"    short: {_typescript_string(definition.short_label)},\n",
                f"    help: {_typescript_string(definition.help)},\n",
                f"    symbol: {_typescript_string(definition.symbol)},\n",
                f"    color: {_typescript_string(definition.color)},\n",
                f"    className: {_typescript_string(definition.css_class)},\n",
                "    evidenceStage: "
                f"{_typescript_string(definition.evidence_stage.name.lower())},\n",
                f"    precedence: {definition.precedence},\n",
                "  },\n",
            ]
        )
    lines.extend(
        [
            "} as const;\n\n",
            "export type Status = keyof typeof STATUS_REGISTRY;\n\n",
            "export const ALL_STATUSES = Object.keys(STATUS_REGISTRY) as Status[];\n\n",
            "export const STATUS_META: Record<\n",
            "  Status,\n",
            "  { label: string; short: string; color: string; className: string }\n",
            "> = Object.fromEntries(\n",
            "  ALL_STATUSES.map((status) => [status, {\n",
            "    label: STATUS_REGISTRY[status].label,\n",
            "    short: STATUS_REGISTRY[status].short,\n",
            "    color: STATUS_REGISTRY[status].color,\n",
            "    className: STATUS_REGISTRY[status].className,\n",
            "  }]),\n",
            ") as Record<Status, { label: string; short: string; color: string; "
            "className: string }>;\n\n",
            "export const STATUS_HELP = Object.fromEntries(\n",
            "  ALL_STATUSES.map((status) => [status, STATUS_REGISTRY[status].help]),\n",
            ") as Record<Status, string>;\n\n",
            "export const STATUS_SYMBOL = Object.fromEntries(\n",
            "  ALL_STATUSES.map((status) => [status, STATUS_REGISTRY[status].symbol]),\n",
            ") as Record<Status, string>;\n",
        ]
    )
    return "".join(lines)


def generated_path() -> Path:
    return (
        Path(__file__).resolve().parents[2]
        / "dashboard"
        / "src"
        / "generated"
        / "statusRegistry.ts"
    )


def main() -> None:
    output = generated_path()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_typescript(), encoding="utf-8", newline="\n")
    print(output)


if __name__ == "__main__":
    main()
