import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const registryPath = path.join(root, "src", "exohunt", "status_registry.json");
const outputPath = path.join(
  root,
  "dashboard",
  "src",
  "generated",
  "statusRegistry.ts",
);
const definitions = JSON.parse(fs.readFileSync(registryPath, "utf8"));

let output =
  "// Generated by `npm run generate:statuses`.\n" +
  "// Do not edit this file; edit src/exohunt/status_registry.json instead.\n\n" +
  "export const STATUS_REGISTRY = {\n";

for (const definition of definitions) {
  output += `  ${JSON.stringify(definition.slug)}: {\n`;
  output += `    label: ${JSON.stringify(definition.label)},\n`;
  output += `    short: ${JSON.stringify(definition.short_label)},\n`;
  output += `    help: ${JSON.stringify(definition.help)},\n`;
  output += `    symbol: ${JSON.stringify(definition.symbol)},\n`;
  output += `    color: ${JSON.stringify(definition.color)},\n`;
  output += `    className: ${JSON.stringify(definition.css_class)},\n`;
  output += `    evidenceStage: ${JSON.stringify(definition.evidence_stage)},\n`;
  output += `    precedence: ${definition.precedence},\n`;
  output += "  },\n";
}

output +=
  "} as const;\n\n" +
  "export type Status = keyof typeof STATUS_REGISTRY;\n\n" +
  "export const ALL_STATUSES = Object.keys(STATUS_REGISTRY) as Status[];\n\n" +
  "export const STATUS_META: Record<\n" +
  "  Status,\n" +
  "  { label: string; short: string; color: string; className: string }\n" +
  "> = Object.fromEntries(\n" +
  "  ALL_STATUSES.map((status) => [status, {\n" +
  "    label: STATUS_REGISTRY[status].label,\n" +
  "    short: STATUS_REGISTRY[status].short,\n" +
  "    color: STATUS_REGISTRY[status].color,\n" +
  "    className: STATUS_REGISTRY[status].className,\n" +
  "  }]),\n" +
  ") as Record<Status, { label: string; short: string; color: string; className: string }>;\n\n" +
  "export const STATUS_HELP = Object.fromEntries(\n" +
  "  ALL_STATUSES.map((status) => [status, STATUS_REGISTRY[status].help]),\n" +
  ") as Record<Status, string>;\n\n" +
  "export const STATUS_SYMBOL = Object.fromEntries(\n" +
  "  ALL_STATUSES.map((status) => [status, STATUS_REGISTRY[status].symbol]),\n" +
  ") as Record<Status, string>;\n";

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output, "utf8");
console.log(outputPath);
